### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by takacsd** [kshpytsya/conan-client-remote-s3#4]
Hi,

found this project and it is exactly what I need! The only problem is it doesn't work with python 3.9.5, it just doesn't install because of the `python <=3.9` rule. (I suppose you meant to make it possible with 3.9.x but it doesn't seem to work.)

But generally that rule seems unnecessary, and it would break 3.10 too. What was the reason for it?

BTW I removed that rule and also in `requests-adapter-injector` and it seems to work fine.

**Comment by kshpytsya** [comment]
Thank you for reporting this. I have just removed the upper Python version constraint from both projects. Released as v0.0.6.

**Comment by takacsd** [comment]
Thanks a lot!
